---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 54310.
--- DateTime: 2026/6/18 10:19
---
if(redis.call('get,KEYS[1]') == ARGV[1]) then
    -- 释放锁
    return redis.call('del',KEYS[1])
end
return 0